[programs.localnet]
lotto = "9sXe1DKZaBGNURjUwKe9EhJrhFGTw8NgGpa9gsZfr3zo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/alper/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
